name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - uses: extractions/setup-just@v2
      - name: Install parent
        run: mvn -B -ntp install -N
      - name: Install tool spec
        run: mvn -B -ntp -f agent-tool-spec/pom.xml install
      - name: Build example tools
        run: just installGetWeather installCodeExchangeRate
      - name: Build with Maven
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: mvn --batch-mode -ntp package
